
# Where things are
source:      ./src
destination: ./dist
layouts:     ./src/layouts
data_source: components

# Handling Reading
exclude:      [
  'img',
  'includes',
  'js',
  'layouts',
  'scss'
]
keep_files: [
  'css',
  'img',
  'js'
]
encoding: 'utf-8'

