# Where things are
source:      ./src
destination: ./dist
layouts:     _layouts
data_source: _includes

# Handling Reading
exclude:      [
  'img',
  'js',
  'scss'
]
keep_files: [
  'css',
  'img',
  'js'
]
encoding: 'utf-8'

